apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubedemoapp-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: kubedemoapp
    template:
      metadata:
        labels:
          app: kubedemoapp
    containers:
      - name: kubedemoapp
        image: srithu/kubedemoapp:sample
        ports:
        - containerPort: 5000
    --type : NodePort

